package com.iqtb.validacion.pojo;
// Generated 04-jun-2014 13:10:04 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private BitacoraId id;
     private String descripcion;
     private Date fecha;
     private String tipo;

    public Bitacora() {
    }

    public Bitacora(BitacoraId id, String descripcion, Date fecha, String tipo) {
       this.id = id;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.tipo = tipo;
    }
   
    public BitacoraId getId() {
        return this.id;
    }
    
    public void setId(BitacoraId id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


