package com.iqtb.validacion.pojo;
// Generated 04-jun-2014 13:10:04 by Hibernate Tools 3.6.0



/**
 * BitacoraId generated by hbm2java
 */
public class BitacoraId  implements java.io.Serializable {


     private int idBitacora;
     private int idUsuario;
     private int idServicio;
     private int idEmpresa;

    public BitacoraId() {
    }

    public BitacoraId(int idBitacora, int idUsuario, int idServicio, int idEmpresa) {
       this.idBitacora = idBitacora;
       this.idUsuario = idUsuario;
       this.idServicio = idServicio;
       this.idEmpresa = idEmpresa;
    }
   
    public int getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(int idBitacora) {
        this.idBitacora = idBitacora;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BitacoraId) ) return false;
		 BitacoraId castOther = ( BitacoraId ) other; 
         
		 return (this.getIdBitacora()==castOther.getIdBitacora())
 && (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdServicio()==castOther.getIdServicio())
 && (this.getIdEmpresa()==castOther.getIdEmpresa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdBitacora();
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdServicio();
         result = 37 * result + this.getIdEmpresa();
         return result;
   }   


}


