package com.iqtb.validacion.pojo;
// Generated 05-jun-2014 10:57:16 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private Integer idBitacora;
     private Integer idUsuario;
     private int idServicio;
     private int idEmpresa;
     private String descripcion;
     private Date fecha;
     private String tipo;

    public Bitacora() {
    }

	
    public Bitacora(int idServicio, int idEmpresa, String descripcion, Date fecha, String tipo) {
        this.idServicio = idServicio;
        this.idEmpresa = idEmpresa;
        this.descripcion = descripcion;
        this.fecha = fecha;
        this.tipo = tipo;
    }
    public Bitacora(Integer idUsuario, int idServicio, int idEmpresa, String descripcion, Date fecha, String tipo) {
       this.idUsuario = idUsuario;
       this.idServicio = idServicio;
       this.idEmpresa = idEmpresa;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.tipo = tipo;
    }
   
    public Integer getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(Integer idBitacora) {
        this.idBitacora = idBitacora;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


