package com.iqtb.validacion.pojo;
// Generated 04-jun-2014 13:10:04 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * CfdisRecibidos generated by hbm2java
 */
public class CfdisRecibidos  implements java.io.Serializable {


     private CfdisRecibidosId id;
     private String serie;
     private Integer folio;
     private String uuid;
     private Date fecha;
     private BigDecimal total;
     private String xmlSat;
     private Date fechaRecepcion;
     private String estado;
     private String error;
     private Byte reportado;

    public CfdisRecibidos() {
    }

	
    public CfdisRecibidos(CfdisRecibidosId id, String uuid, Date fecha, BigDecimal total, String xmlSat, Date fechaRecepcion, String estado) {
        this.id = id;
        this.uuid = uuid;
        this.fecha = fecha;
        this.total = total;
        this.xmlSat = xmlSat;
        this.fechaRecepcion = fechaRecepcion;
        this.estado = estado;
    }
    public CfdisRecibidos(CfdisRecibidosId id, String serie, Integer folio, String uuid, Date fecha, BigDecimal total, String xmlSat, Date fechaRecepcion, String estado, String error, Byte reportado) {
       this.id = id;
       this.serie = serie;
       this.folio = folio;
       this.uuid = uuid;
       this.fecha = fecha;
       this.total = total;
       this.xmlSat = xmlSat;
       this.fechaRecepcion = fechaRecepcion;
       this.estado = estado;
       this.error = error;
       this.reportado = reportado;
    }
   
    public CfdisRecibidosId getId() {
        return this.id;
    }
    
    public void setId(CfdisRecibidosId id) {
        this.id = id;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public Integer getFolio() {
        return this.folio;
    }
    
    public void setFolio(Integer folio) {
        this.folio = folio;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getXmlSat() {
        return this.xmlSat;
    }
    
    public void setXmlSat(String xmlSat) {
        this.xmlSat = xmlSat;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }
    public Byte getReportado() {
        return this.reportado;
    }
    
    public void setReportado(Byte reportado) {
        this.reportado = reportado;
    }




}


