package com.iqtb.validacion.pojo;
// Generated 04-jun-2014 13:10:04 by Hibernate Tools 3.6.0



/**
 * ConfiguracionesServiciosId generated by hbm2java
 */
public class ConfiguracionesServiciosId  implements java.io.Serializable {


     private int idConfiguracionServicio;
     private int idServicio;

    public ConfiguracionesServiciosId() {
    }

    public ConfiguracionesServiciosId(int idConfiguracionServicio, int idServicio) {
       this.idConfiguracionServicio = idConfiguracionServicio;
       this.idServicio = idServicio;
    }
   
    public int getIdConfiguracionServicio() {
        return this.idConfiguracionServicio;
    }
    
    public void setIdConfiguracionServicio(int idConfiguracionServicio) {
        this.idConfiguracionServicio = idConfiguracionServicio;
    }
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConfiguracionesServiciosId) ) return false;
		 ConfiguracionesServiciosId castOther = ( ConfiguracionesServiciosId ) other; 
         
		 return (this.getIdConfiguracionServicio()==castOther.getIdConfiguracionServicio())
 && (this.getIdServicio()==castOther.getIdServicio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdConfiguracionServicio();
         result = 37 * result + this.getIdServicio();
         return result;
   }   


}


