package com.iqtb.validacion.pojo;
// Generated 04-jun-2014 13:10:04 by Hibernate Tools 3.6.0



/**
 * ConfiguracionesEmpresasId generated by hbm2java
 */
public class ConfiguracionesEmpresasId  implements java.io.Serializable {


     private int idConfiguracionEmpresa;
     private int idEmpresa;

    public ConfiguracionesEmpresasId() {
    }

    public ConfiguracionesEmpresasId(int idConfiguracionEmpresa, int idEmpresa) {
       this.idConfiguracionEmpresa = idConfiguracionEmpresa;
       this.idEmpresa = idEmpresa;
    }
   
    public int getIdConfiguracionEmpresa() {
        return this.idConfiguracionEmpresa;
    }
    
    public void setIdConfiguracionEmpresa(int idConfiguracionEmpresa) {
        this.idConfiguracionEmpresa = idConfiguracionEmpresa;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConfiguracionesEmpresasId) ) return false;
		 ConfiguracionesEmpresasId castOther = ( ConfiguracionesEmpresasId ) other; 
         
		 return (this.getIdConfiguracionEmpresa()==castOther.getIdConfiguracionEmpresa())
 && (this.getIdEmpresa()==castOther.getIdEmpresa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdConfiguracionEmpresa();
         result = 37 * result + this.getIdEmpresa();
         return result;
   }   


}


