package com.iqtb.validacion.pojo;
// Generated 04-jun-2014 13:10:04 by Hibernate Tools 3.6.0



/**
 * Opciones generated by hbm2java
 */
public class Opciones  implements java.io.Serializable {


     private OpcionesId id;
     private String opcion;
     private String href;
     private String descripcion;
     private String tipo;

    public Opciones() {
    }

	
    public Opciones(OpcionesId id, String opcion) {
        this.id = id;
        this.opcion = opcion;
    }
    public Opciones(OpcionesId id, String opcion, String href, String descripcion, String tipo) {
       this.id = id;
       this.opcion = opcion;
       this.href = href;
       this.descripcion = descripcion;
       this.tipo = tipo;
    }
   
    public OpcionesId getId() {
        return this.id;
    }
    
    public void setId(OpcionesId id) {
        this.id = id;
    }
    public String getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }
    public String getHref() {
        return this.href;
    }
    
    public void setHref(String href) {
        this.href = href;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


