package com.iqtb.validacion.pojo;
// Generated 04-jun-2014 13:10:04 by Hibernate Tools 3.6.0



/**
 * OpcionesId generated by hbm2java
 */
public class OpcionesId  implements java.io.Serializable {


     private int idOpcion;
     private int idPestania;

    public OpcionesId() {
    }

    public OpcionesId(int idOpcion, int idPestania) {
       this.idOpcion = idOpcion;
       this.idPestania = idPestania;
    }
   
    public int getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(int idOpcion) {
        this.idOpcion = idOpcion;
    }
    public int getIdPestania() {
        return this.idPestania;
    }
    
    public void setIdPestania(int idPestania) {
        this.idPestania = idPestania;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OpcionesId) ) return false;
		 OpcionesId castOther = ( OpcionesId ) other; 
         
		 return (this.getIdOpcion()==castOther.getIdOpcion())
 && (this.getIdPestania()==castOther.getIdPestania());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOpcion();
         result = 37 * result + this.getIdPestania();
         return result;
   }   


}


