package com.iqtb.validacion.pojo;
// Generated 18-jul-2014 19:02:45 by Hibernate Tools 3.6.0



/**
 * Pestanias generated by hbm2java
 */
public class Pestanias  implements java.io.Serializable {


     private Integer idPestania;
     private String nombre;
     private int orden;

    public Pestanias() {
    }

    public Pestanias(String nombre, int orden) {
       this.nombre = nombre;
       this.orden = orden;
    }
   
    public Integer getIdPestania() {
        return this.idPestania;
    }
    
    public void setIdPestania(Integer idPestania) {
        this.idPestania = idPestania;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }




}


