package com.iqtb.validacion.pojo;
// Generated 18-jul-2014 19:02:45 by Hibernate Tools 3.6.0



/**
 * Plantillas generated by hbm2java
 */
public class Plantillas  implements java.io.Serializable {


     private Integer idPlantillas;
     private int idEmpresa;
     private String nombre;
     private String ruta;
     private String sha1;

    public Plantillas() {
    }

    public Plantillas(int idEmpresa, String nombre, String ruta, String sha1) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.ruta = ruta;
       this.sha1 = sha1;
    }
   
    public Integer getIdPlantillas() {
        return this.idPlantillas;
    }
    
    public void setIdPlantillas(Integer idPlantillas) {
        this.idPlantillas = idPlantillas;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getSha1() {
        return this.sha1;
    }
    
    public void setSha1(String sha1) {
        this.sha1 = sha1;
    }




}


