package com.iqtb.validacion.pojo;
// Generated 18-jul-2014 19:02:45 by Hibernate Tools 3.6.0



/**
 * Respaldos generated by hbm2java
 */
public class Respaldos  implements java.io.Serializable {


     private Integer idRespaldo;

    public Respaldos() {
    }

   
    public Integer getIdRespaldo() {
        return this.idRespaldo;
    }
    
    public void setIdRespaldo(Integer idRespaldo) {
        this.idRespaldo = idRespaldo;
    }




}


