package com.iqtb.validacion.pojo;
// Generated 05-jun-2014 10:57:16 by Hibernate Tools 3.6.0



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idRol;
     private String tipo;
     private String nombre;

    public Roles() {
    }

    public Roles(String tipo, String nombre) {
       this.tipo = tipo;
       this.nombre = nombre;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


