package com.iqtb.validacion.pojo;
// Generated 18-jul-2014 19:02:45 by Hibernate Tools 3.6.0



/**
 * RolesHasOpciones generated by hbm2java
 */
public class RolesHasOpciones  implements java.io.Serializable {


     private RolesHasOpcionesId id;

    public RolesHasOpciones() {
    }

    public RolesHasOpciones(RolesHasOpcionesId id) {
       this.id = id;
    }
   
    public RolesHasOpcionesId getId() {
        return this.id;
    }
    
    public void setId(RolesHasOpcionesId id) {
        this.id = id;
    }




}


