package com.iqtb.validacion.pojo;
// Generated 23-jun-2014 17:36:10 by Hibernate Tools 3.6.0



/**
 * UsuariosHasEmpresas generated by hbm2java
 */
public class UsuariosHasEmpresas  implements java.io.Serializable {


     private UsuariosHasEmpresasId id;

    public UsuariosHasEmpresas() {
    }

    public UsuariosHasEmpresas(UsuariosHasEmpresasId id) {
       this.id = id;
    }
   
    public UsuariosHasEmpresasId getId() {
        return this.id;
    }
    
    public void setId(UsuariosHasEmpresasId id) {
        this.id = id;
    }




}


