package com.iqtb.validacion.pojo;
// Generated 03-jun-2014 18:54:48 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private UsuariosId id;
     private String email;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String passkey;
     private String salt;
     private Date dateExpirationPass;
     private Date lastAction;
     private String estado;
     private String userid;
     private Date fechaAlta;
     private int intentosFallidos;

    public Usuarios() {
    }

	
    public Usuarios(UsuariosId id, String email, String nombre, String apaterno, String passkey, String salt, Date dateExpirationPass, Date lastAction, String estado, String userid, Date fechaAlta, int intentosFallidos) {
        this.id = id;
        this.email = email;
        this.nombre = nombre;
        this.apaterno = apaterno;
        this.passkey = passkey;
        this.salt = salt;
        this.dateExpirationPass = dateExpirationPass;
        this.lastAction = lastAction;
        this.estado = estado;
        this.userid = userid;
        this.fechaAlta = fechaAlta;
        this.intentosFallidos = intentosFallidos;
    }
    public Usuarios(UsuariosId id, String email, String nombre, String apaterno, String amaterno, String passkey, String salt, Date dateExpirationPass, Date lastAction, String estado, String userid, Date fechaAlta, int intentosFallidos) {
       this.id = id;
       this.email = email;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.passkey = passkey;
       this.salt = salt;
       this.dateExpirationPass = dateExpirationPass;
       this.lastAction = lastAction;
       this.estado = estado;
       this.userid = userid;
       this.fechaAlta = fechaAlta;
       this.intentosFallidos = intentosFallidos;
    }
   
    public UsuariosId getId() {
        return this.id;
    }
    
    public void setId(UsuariosId id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getPasskey() {
        return this.passkey;
    }
    
    public void setPasskey(String passkey) {
        this.passkey = passkey;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public Date getDateExpirationPass() {
        return this.dateExpirationPass;
    }
    
    public void setDateExpirationPass(Date dateExpirationPass) {
        this.dateExpirationPass = dateExpirationPass;
    }
    public Date getLastAction() {
        return this.lastAction;
    }
    
    public void setLastAction(Date lastAction) {
        this.lastAction = lastAction;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public int getIntentosFallidos() {
        return this.intentosFallidos;
    }
    
    public void setIntentosFallidos(int intentosFallidos) {
        this.intentosFallidos = intentosFallidos;
    }




}


