package com.iqtb.validacion.pojo;
// Generated 03-jun-2014 18:54:48 by Hibernate Tools 3.6.0



/**
 * UsuariosId generated by hbm2java
 */
public class UsuariosId  implements java.io.Serializable {


     private int idUsuario;
     private int idRol;

    public UsuariosId() {
    }

    public UsuariosId(int idUsuario, int idRol) {
       this.idUsuario = idUsuario;
       this.idRol = idRol;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuariosId) ) return false;
		 UsuariosId castOther = ( UsuariosId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdRol()==castOther.getIdRol());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdRol();
         return result;
   }   


}


